# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('message', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inventory', models.IntegerField()),
                ('grade', models.CharField(max_length=200)),
                ('gradedBy', models.IntegerField()),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommodityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginName', models.CharField(max_length=200)),
                ('loginPwd', models.CharField(max_length=200)),
                ('nickName', models.CharField(max_length=200)),
                ('dftAddress', models.TextField()),
                ('dftPayType', models.IntegerField()),
                ('contact', models.TextField()),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('payType', models.IntegerField()),
                ('message', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time', models.DateTimeField()),
                ('state', models.IntegerField()),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Commodity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('intro', models.TextField()),
                ('createDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShopKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginName', models.CharField(max_length=200)),
                ('loginPwd', models.CharField(max_length=200)),
                ('nickName', models.CharField(max_length=200)),
                ('contact', models.TextField()),
                ('email', models.TextField()),
                ('account', models.CharField(max_length=200)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.ShopCategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Shop'),
        ),
        migrations.AddField(
            model_name='grading',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Shop'),
        ),
        migrations.AddField(
            model_name='commoditycategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.ShopCategory'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='categoty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.CommodityCategory'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Shop'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Commodity'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Commodity'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Cart'),
        ),
        migrations.AddField(
            model_name='cart',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Consumer'),
        ),
    ]
