# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('message', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('inventory', models.IntegerField(default=0)),
                ('grade', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('gradedBy', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGouApp.CommodityCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(default='No nickName', max_length=200)),
                ('dftAddress', models.TextField(blank=True, null=True)),
                ('dftPayType', models.CharField(default='aliPay', max_length=200)),
                ('contact', models.TextField(blank=True, null=True)),
                ('grade', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('gradedBy', models.IntegerField(default=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConsumerProf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=200)),
                ('payType', models.CharField(default='aliPay', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('time', models.DateTimeField()),
                ('state', models.IntegerField(default=0)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Commodity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('intro', models.TextField()),
                ('createDate', models.DateTimeField()),
                ('grade', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('gradedBy', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGouApp.ShopCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ShopKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(default='No nickName', max_length=200)),
                ('contact', models.TextField(null=True)),
                ('account', models.CharField(max_length=200, null=True)),
                ('shop', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ShopKeeper', to='TGouApp.Shop')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ShopKeeperProf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGouApp.ShopCategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Shop'),
        ),
        migrations.AddField(
            model_name='grading',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Shop'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGouApp.CommodityCategory'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Shop'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Commodity'),
        ),
        migrations.AddField(
            model_name='comment',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Consumer'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Commodity'),
        ),
        migrations.AddField(
            model_name='cart',
            name='consumer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='TGouApp.Consumer'),
        ),
    ]
