# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='categoty',
            new_name='category',
        ),
    ]
