# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TGouApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='loginName',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='loginPwd',
        ),
        migrations.AddField(
            model_name='consumer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='contact',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='dftAddress',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='dftPayType',
            field=models.IntegerField(blank=True),
        ),
    ]
