# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0002_auto_20160725_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='shop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ShopKeeper', to='TGouApp.Shop'),
        ),
    ]
