# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0002_auto_20160722_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='dftAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='dftPayType',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
