# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0003_auto_20160726_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='gradedBy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
