# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 23:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TGouApp', '0003_auto_20160722_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopkeeper',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='loginName',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='loginPwd',
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
