# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0004_auto_20160722_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='account',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='contact',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='nickName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Shop'),
        ),
    ]
