# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0004_auto_20160726_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
