# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0005_auto_20160727_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='consumer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='TGouApp.Consumer'),
        ),
    ]
