# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 03:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0005_auto_20160722_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='nickName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConsumerProf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='nickName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ShopKeeperProf', to=settings.AUTH_USER_MODEL),
        ),
    ]
