# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0006_auto_20160727_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='order',
            new_name='cart',
        ),
    ]
