# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0007_auto_20160727_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TGouApp.Cart'),
        ),
    ]
