# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0008_auto_20160728_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='payType',
            field=models.IntegerField(default=0),
        ),
    ]
