# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0010_auto_20160728_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditycategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TGouApp.CommodityCategory'),
        ),
    ]
