# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0012_shopcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='nickName',
            field=models.CharField(default='No nickName', max_length=200),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='nickName',
            field=models.CharField(default='No nickName', max_length=200),
        ),
    ]
