# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0013_auto_20160728_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='consumer',
            name='gradedBy',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shop',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='shop',
            name='gradedBy',
            field=models.IntegerField(default=1),
        ),
    ]
