# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGouApp', '0014_auto_20160728_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='dftPayType',
            field=models.CharField(default='aliPay', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='payType',
            field=models.CharField(default='aliPay', max_length=200),
        ),
    ]
